#!/bin/bash -e

. /usr/share/debconf/confmodule

export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin

# This command can be used as pipe to syslog. With "-s" it also logs to stderr.
ERR_LOGGER="logger -p daemon.err -t hugnetlab -i -s"



db_input critical hugnetlab/mysql_root_user || true
db_go

db_input critical hugnetlab/mysql_root_pw || true
db_go

db_input medium hugnetlab/mysql_user || true
db_go

db_input medium hugnetlab/mysql_pw || true
db_go


db_get hugnetlab/mysql_pw

if [ -n "$RET" ]; then
    mysql_pw=${RET}
else
    mysql_pw=`cat /dev/urandom|tr -dc "a-zA-Z0-9\!_"|head -c 15`
fi
db_set hugnetlab/mysql_pw ${mysql_pw}


exit 0